// src/config/yaml.ts
// ESPHome YAML configuration generator

interface YAMLParams {
  t: number;
  hc: number;
  n: number;
  s: number;
  min: number;
  max: number;
  pid: boolean;
  kp: number;
  ki: number;
  kd: number;
  db: boolean;
  th: number;
  tl: number;
  kpm: number;
  kim?: number;
  kdm?: number;
}

interface YAMLOptions {
  includeSensors?: boolean;
  includeNumbers?: boolean;
}

/**
 * Format number for YAML output - strip trailing zeros but keep one decimal
 */
function fmt(val: number, decimals: number = 2): string {
  let s = val.toFixed(decimals);
  s = s.replace(/0+$/, '');
  if (s.endsWith('.')) s = s.slice(0, -1) + '.0';
  return s;
}

/**
 * Generate ESPHome YAML configuration from config data
 */
export function generateYAML(p: YAMLParams, options: YAMLOptions = {}): string {
  const { includeSensors = false, includeNumbers = false } = options;

  // Build optional lines
  const shiftLine = p.s !== 0 ? `\n        shift: ${fmt(p.s, 1)}` : '';

  // Build PID section (only include non-zero values)
  let pidLines = '';
  if (p.pid) {
    if (p.kp !== 0) pidLines += `\n        kp: ${fmt(p.kp)}`;
    if (p.ki !== 0) pidLines += `\n        ki: ${fmt(p.ki, 3)}`;
    if (p.kd !== 0) pidLines += `\n        kd: ${fmt(p.kd)}`;
  }

  // Build deadband section
  let deadbandSection = '';
  if (p.db) {
    deadbandSection = `
      deadband_parameters:
        threshold_high: ${fmt(p.th, 1)}
        threshold_low: ${fmt(p.tl, 1)}`;
    if (p.kpm !== 0.1) deadbandSection += `\n        kp_multiplier: ${fmt(p.kpm)}`;
    if (p.kim !== undefined && p.kim !== 0) deadbandSection += `\n        ki_multiplier: ${fmt(p.kim)}`;
    if (p.kdm !== undefined && p.kdm !== 0) deadbandSection += `\n        kd_multiplier: ${fmt(p.kdm)}`;
  }

  // Build diagnostic sensors section
  let sensorsSection = '';
  if (includeSensors) {
    sensorsSection = `

  # Diagnostic sensors
  - platform: equitherm
    climate_id: heating_controller
    type: curve_output_raw
    name: "Curve Output Raw"
  - platform: equitherm
    climate_id: heating_controller
    type: final_flow_setpoint
    name: "Final Flow Setpoint"`;

    if (p.pid) {
      sensorsSection += `
  - platform: equitherm
    climate_id: heating_controller
    type: pid_correction
    name: "PID Correction"`;
    }

    sensorsSection += `

binary_sensor:
  - platform: equitherm
    climate_id: heating_controller
    outdoor_fallback_active:
      name: "Outdoor Sensor Fallback"
    rate_limiting_active:
      name: "Rate Limiting Active"

text_sensor:
  - platform: equitherm
    climate_id: heating_controller
    control_mode:
      name: "Control Mode"`;
  }

  // Build runtime tuning numbers section
  let numbersSection = '';
  if (includeNumbers) {
    numbersSection = `

number:
  - platform: equitherm
    climate_id: heating_controller
    heat_curve_coefficient:
      name: "Heating Curve Coefficient"
    heat_curve_exponent:
      name: "Heating Curve Exponent"`;
    if (p.s !== 0) {
      numbersSection += `
    heat_curve_shift:
      name: "Heating Curve Shift"`;
    }
    if (p.pid) {
      numbersSection += `
    pid_proportional_gain:
      name: "PID Proportional Gain"
    pid_integral_gain:
      name: "PID Integral Gain"
    pid_derivative_gain:
      name: "PID Derivative Gain"`;
    }
  }

  return `# Generated by Equitherm Calculator
# ${new Date().toISOString().split('T')[0]}

climate:
  - platform: equitherm
    id: heating_controller
    name: Equitherm Climate
    outdoor_sensor: outdoor_sensor
    indoor_sensor: indoor_sensor
    default_target_temperature: ${p.t}
    heat_output: heat_output
    fallback_outdoor_temp: 0.0
    control_parameters:
      hc: ${fmt(p.hc)}
      n: ${fmt(p.n)}${shiftLine}${pidLines}
    output_parameters:
      min_flow_temp: ${p.min}
      max_flow_temp: ${p.max}${deadbandSection}

sensor:${sensorsSection}${numbersSection}
`;
}
